site_name: SBI Sandbox
site_url: https://binado.github.io/sbisandbox
repo_name: sbisandbox
repo_url: https://github.com/binado/sbisandbox
site_author: Bernardo Porto Veronese
theme:
  name: material
nav:
  - Home: index.md
  - Resources: resources.md
  - Tutorials:
      - Introduction: tutorials/introduction.md
markdown_extensions:
  - toc:
      permalink: true
      separator: "_"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
