site_name: SBI Sandbox
site_url: https://binado.github.io/sbisandbox
repo_name: sbisandbox
repo_url: https://github.com/binado/sbisandbox
site_author: Bernardo Porto Veronese
theme:
  name: material
  favicon: img/favicon.png
  icon:
    logo: material/book
  font:
    text: Inter
  features:
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7

        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - About: about.md
  - Installation: install.md
  - Glossary:
      - glossary/amortization.md
      - glossary/nle.md
      - glossary/npe.md
      - glossary/nre.md
      - glossary/nflow.md
      - glossary/simulator.md
  - Tutorials:
      - Introduction: tutorials/introduction.md
      - Sequential x amortized: tutorials/twomoons.md
  - Benchmarks:
      - Gaussian Linear: benchmarks/gaussian_linear.md
      - Gaussian Linear Uniform: benchmarks/gaussian_linear_uniform.md
      - Gaussian Mixture: benchmarks/gaussian_mixture.md
      - SLCP: benchmarks/slcp.md
      - Two Moons: benchmarks/two_moons.md
  - Resources: resources.md
markdown_extensions:
  - toc:
      permalink: true
      separator: "_"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

watch:
  - sbisandbox/
